import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, RedirectToSignIn, SignedIn, SignedOut } from '@clerk/nextjs'
import { Separator } from "@/components/ui/separator";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body
        className={cn(geistSans.className, "dark")}
        style={{
          colorScheme: "dark"
        }}
      >
        <header>
            <SignedOut>
            <RedirectToSignIn />
            </SignedOut>
            <SignedIn>
            </SignedIn>
        </header>
        <ThemeProvider>
          <div className="flex min-h-screen w-full flex-col items-center dark:bg-black">
            <Navbar />
            <Separator />
            <main className="flex flex-grow w-full  dark:bg-neutral-950">
              {children}
              <Toaster />
            </main>
          </div>
        </ThemeProvider>
        
      </body>
    </html>
    </ClerkProvider>
    
  );
}
